# Generated by Django 4.2.3 on 2023-07-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_deal_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.CharField(max_length=100),
        ),
    ]
