# Generated by Django 4.2.3 on 2023-07-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_deal_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gems',
            field=models.ManyToManyField(to='api.gem'),
        ),
        migrations.AddField(
            model_name='client',
            name='money_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gem'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gem',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
