# Generated by Django 4.2.3 on 2023-07-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_gems_client_money_spent_alter_client_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gems',
        ),
        migrations.RemoveField(
            model_name='client',
            name='money_spent',
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='api.client'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
