# Generated by Django 4.2.3 on 2023-07-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_client_gems_remove_client_money_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='gems',
            field=models.ManyToManyField(related_name='deals', to='api.gem'),
        ),
    ]
